print("Hello")
input("")
print('We are going to make hundred from letter 1-9')
print("Author : Aadim Gyawali")
print('''Note : You can't use "0"''')
num1 = input("Please say any number from 1-9:")
num1 = int(num1)
if (num1<10):
    print(num1+num1)
    input("")
    print(num1+num1+num1)
    input("")
    print((num1+num1+num1)*2)
    input("")
    print(((num1+num1+num1)*2)-num1)
    input("")
    print((((num1+num1+num1)*2)-num1)/num1)
    input("")
    print(((((num1+num1+num1)*2)-num1)/num1)*10)
    input("")
    print((((((num1+num1+num1)*2)-num1)/num1)*10)*2)
    input("")
    print("Thank you for playing !!!")
    input("")


else:
    print("Please say any number from 1-9")
    input("")
